from __future__ import annotations

import os
from datetime import datetime, timezone

from agri_common import DataSource, ModelUsed, RecommendationEnvelope, RiskAnalysis, RiskLevel
from fastapi import FastAPI

from . import chat
from .schemas import ChatRequest, ChatResult

app = FastAPI(title="AI Chat (Farm Advisor)", version="0.1.0")

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")

# Fixed/generated response text (not model output) — same convention as
# disease_kb/app/main.py's _STRINGS.
_STRINGS: dict[str, dict[str, str]] = {
    "not_configured_reply": {
        "en": "AI chat isn't available right now — no AI API key is configured on this backend yet.",
        "ta": "AI அரட்டை இப்போது கிடைக்கவில்லை — இந்த பின்தளத்தில் இன்னும் AI API கீ அமைக்கப்படவில்லை.",
    },
    "not_configured_source": {"en": "AI chat (not configured)", "ta": "AI அரட்டை (அமைக்கப்படவில்லை)"},
    "not_configured_assumption": {
        "en": "No LLM API key is configured on this backend, so this is a placeholder reply, not a real answer.",
        "ta": "இந்த பின்தளத்தில் LLM API கீ அமைக்கப்படவில்லை, எனவே இது ஒரு வைத்திருப்பு பதில், உண்மையான பதில் அல்ல.",
    },
    "not_configured_reasoning": {
        "en": "Chat requires a configured LLM API key; that step is not yet available.",
        "ta": "அரட்டைக்கு அமைக்கப்பட்ட LLM API கீ தேவை; அந்த படி இன்னும் கிடைக்கவில்லை.",
    },
    "failed_reply": {
        "en": "Sorry, I couldn't answer that just now — please try again in a moment.",
        "ta": "மன்னிக்கவும், இப்போது அதற்கு பதிலளிக்க முடியவில்லை — சிறிது நேரத்தில் மீண்டும் முயற்சிக்கவும்.",
    },
    "failed_source": {"en": "AI chat (temporarily unavailable)", "ta": "AI அரட்டை (தற்காலிகமாக கிடைக்கவில்லை)"},
    "failed_assumption": {
        "en": "The AI chat service returned an error or an empty response for this question — "
        "this is a temporary issue, not a real answer.",
        "ta": "இந்த கேள்விக்கு AI அரட்டை சேவை ஒரு பிழையை அல்லது வெற்று பதிலை வழங்கியது — இது ஒரு தற்காலிக "
        "சிக்கல், உண்மையான பதில் அல்ல.",
    },
    "failed_reasoning": {
        "en": "The chat completion call failed or returned no usable text for this request.",
        "ta": "இந்த கோரிக்கைக்கு அரட்டை முடிவு அழைப்பு தோல்வியடைந்தது அல்லது பயன்படுத்தக்கூடிய உரையை வழங்கவில்லை.",
    },
    "no_answer_risk_factor": {
        "en": "No AI-generated answer was produced for this question.",
        "ta": "இந்த கேள்விக்கு AI-உருவாக்கிய பதில் எதுவும் தயாரிக்கப்படவில்லை.",
    },
    "success_source": {
        "en": "Claude Opus 4.8, grounded in this farm's dashboard context",
        "ta": "க்ளாட் ஓபஸ் 4.8, இந்த பண்ணையின் டாஷ்போர்டு தரவை அடிப்படையாகக் கொண்டது",
    },
    "success_assumption": {
        "en": "This answer is generated by an AI model grounded in your farm's current dashboard data — "
        "treat it as helpful guidance, not a substitute for expert agricultural advice.",
        "ta": "இந்த பதில் உங்கள் பண்ணையின் தற்போதைய டாஷ்போர்டு தரவை அடிப்படையாகக் கொண்ட AI மாதிரியால் "
        "உருவாக்கப்பட்டது — இதை பயனுள்ள வழிகாட்டுதலாக கருதவும், நிபுணர் வேளாண் ஆலோசனைக்கு மாற்றாக அல்ல.",
    },
    "success_reasoning": {
        "en": "Answered using the farmer's question, recent conversation history, and this farm's "
        "current dashboard context.",
        "ta": "விவசாயியின் கேள்வி, சமீபத்திய உரையாடல் வரலாறு மற்றும் இந்த பண்ணையின் தற்போதைய டாஷ்போர்டு "
        "தரவைப் பயன்படுத்தி பதிலளிக்கப்பட்டது.",
    },
    "action_verify": {
        "en": "For disease or pest questions, use the photo diagnosis feature for a properly grounded answer.",
        "ta": "நோய் அல்லது பூச்சி கேள்விகளுக்கு, சரியாக அடிப்படையிலான பதிலுக்கு புகைப்பட கண்டறிதல் "
        "அம்சத்தைப் பயன்படுத்தவும்.",
    },
}


def _t(key: str, language: str) -> str:
    return _STRINGS[key].get(language, _STRINGS[key]["en"])


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/chat/ask", response_model=RecommendationEnvelope[ChatResult])
def ask(req: ChatRequest) -> RecommendationEnvelope[ChatResult]:
    """Single grounded Claude call — not a multi-step agent loop, the same
    "simpler, cheaper, more predictable" choice already documented for the
    LogicApp Monitor Agent this pattern is modeled on. See app/chat.py."""
    now = datetime.now(timezone.utc)
    language = req.language

    if not ANTHROPIC_API_KEY:
        return RecommendationEnvelope[ChatResult](
            result=ChatResult(reply=_t("not_configured_reply", language)),
            confidence_score=0.0,
            data_sources=[DataSource(name=_t("not_configured_source", language), as_of=now, live=False)],
            assumptions=[_t("not_configured_assumption", language)],
            reasoning=_t("not_configured_reasoning", language),
            model_used=None,
            risk_analysis=RiskAnalysis(level=RiskLevel.LOW, factors=[_t("no_answer_risk_factor", language)]),
            action_plan=[],
        )

    reply = chat.ask(req=req, api_key=ANTHROPIC_API_KEY)

    if reply is None:
        return RecommendationEnvelope[ChatResult](
            result=ChatResult(reply=_t("failed_reply", language)),
            confidence_score=0.0,
            data_sources=[DataSource(name=_t("failed_source", language), as_of=now, live=False)],
            assumptions=[_t("failed_assumption", language)],
            reasoning=_t("failed_reasoning", language),
            model_used=ModelUsed(name="claude-opus-4-8", version="0.1.0"),
            risk_analysis=RiskAnalysis(level=RiskLevel.LOW, factors=[_t("no_answer_risk_factor", language)]),
            action_plan=[],
        )

    return RecommendationEnvelope[ChatResult](
        result=ChatResult(reply=reply),
        confidence_score=0.7,
        data_sources=[DataSource(name=_t("success_source", language), as_of=now, live=True)],
        assumptions=[_t("success_assumption", language)],
        reasoning=_t("success_reasoning", language),
        model_used=ModelUsed(name="claude-opus-4-8", version="0.1.0"),
        risk_analysis=None,
        action_plan=[_t("action_verify", language)],
    )
